### ISSUE TITLE
how to deply it on deta by myself?

### ISSUE THREAD

**Issue by 8ty** [minlaxz/warp-plus#30]
have a guidance? i want step by step one

**Comment by minlaxz** [comment]
I think it should be fairly simple to deploy on [deta](deta.sh). I'm afraid that I can't remember the steps as it's about a year long.
But I made a quick search for you, and I believe that it's called micros. 

For more detail, please go [here](https://docs.deta.sh/docs/micros/getting_started) for about and [here](https://docs.deta.sh/docs/micros/deploy) for deployment.

Good luck.
