### ISSUE TITLE
Usage: python -m flask run [OPTIONS] error: Could not locate a Flask application.

### ISSUE THREAD

**Issue by xleo712** [minlaxz/warp-plus#8]
Hi Minlaxz,
I run this pj with Docker desktop
When I run it shows this log
* Environment: production
WARNING: This is a development server. Do not use it in a production deployment.
Use a production WSGI server instead.
* Debug mode: off
Usage: python -m flask run [OPTIONS]
Error: Could not locate a Flask application. You did not provide the "FLASK_APP" environment variable, and a "wsgi.py" or "app.py" module was not found in the current directory.

Flask python installed.

**Comment by minlaxz** [comment]
It is normal for this, I just used development environment of flask.
If you prefer for production environment [read here](https://flask.palletsprojects.com/en/2.0.x/tutorial/deploy/)
Sorry for late reply, I didn't use to check issue tab 😂
